dev:
  catalog: mlops_dev
  schema: arxiv
  volume: arxiv_papers
  genie_space_id: 01f0e97a42981382b3d16f3f1899fdb5
  llm_endpoint: databricks-gpt-oss-120b

acc:
  catalog: mlops_acc
  schema: arxiv
  volume: arxiv_papers
  genie_space_id: 01f0e97a42981382b3d16f3f1899fdb5
  llm_endpoint: databricks-gpt-oss-120b

prd:
  catalog: mlops_prd
  schemae: arxiv
  volumee: arxiv_papers
  genie_space_id: 01f0e97a42981382b3d16f3f1899fdb5
  llm_endpoint: databricks-gpt-oss-120b
