dev:
  catalog_name: mlops_dev
  schema_name: arxiv
  volume_name: arxiv_papers
  genie_space_id: 01f0c3f882e41bb9be96b4ddf295d2a4

acc:
  catalog_name: mlops_acc
  schema_name: arxiv
  volume_name: arxiv_papers
  genie_space_id: 01f0c3f882e41bb9be96b4ddf295d2a4

prd:
  catalog_name: mlops_prd
  schema_name: arxiv
  volume_name: arxiv_papers
  genie_space_id: 01f0c3f882e41bb9be96b4ddf295d2a4

model_config:
